### ISSUE TITLE
Host validation

### ISSUE THREAD

**Issue by moty66** [drego85/DDoS-PHP-Script#11]
Validate the host before start sending packets

**Comment by TheZ3ro** [comment]
How we can do this?

Maybe checking if it's an IP ([ip2long($ip)!=FALSE](https://secure.php.net/manual/en/function.ip2long.php)) or and hostname and then using [gethostbyname()](https://secure.php.net/manual/en/function.gethostbyname.php)?

Will this slow down the script? (it's a DNS request)

**Comment by moty66** [comment]
secondo me bastano un paio di regex per verificare se il formato del host è valido o meno.
non dovrebbe rallentare lo script

per l'indirizzo ip, possiamo usare http://php.net/manual/en/filter.filters.validate.php
per il host 

per un host, possiamo usare una cosa così

<pre>
function is_valid_domain_name($domain_name)
{
    return (preg_match("/^([a-z\d](-*[a-z\d])*)(\.([a-z\d](-*[a-z\d])*))*$/i", $domain_name) //valid chars check
            && preg_match("/^.{1,253}$/", $domain_name) //overall length check
            && preg_match("/^[^\.]{1,63}(\.[^\.]{1,63})*$/", $domain_name)   ); //length of each label
}
</pre>

che ne dite?

**Comment by TheZ3ro** [comment]
A questo punto un filtro con `FILTER_VALIDATE_IP` è meglio cosi validiamo sia IPv4 e IPv6,
per l'hostname credo che più di una regex non si possa fare.

Tanto nel caso la connessione venga rifiutata da errore nel udp_connection :v:

**Comment by moty66** [comment]
Posso pensarci io, assegnate a me

m.

**Comment by TheZ3ro** [comment]
Posso assegnare solo ad altri collab :cry: 
Vabbe pensaci comunque tu :smile:
