### ISSUE TITLE
Loggin to file

### ISSUE THREAD

**Issue by moty66** [drego85/DDoS-PHP-Script#12]
Add a new parameter for file logging

**Comment by moty66** [comment]
Come va gestito il logging?
Credo che sia poco utile, visto che la maggior parte del output è PUNTINI PUNTINI

**Comment by drego85** [comment]
Lasciamola nella To-Do List, non è affatto una priorità! Anzi onestamente non è proprio fondamentale!

**Comment by moty66** [comment]
fixed in 41bf6d6
