### ISSUE TITLE
Random port

### ISSUE THREAD

**Issue by moty66** [drego85/DDoS-PHP-Script#16]
Secondo me, potrebbe essere molto efficace un attacco con porte random

Quindi farei  `fsockopen` sempre con porte diverse

**Comment by drego85** [comment]
Hai perfettamente ragione, inizialmente funzionava proprio così! fsockopen era annidato all'interno di un ciclo while e ad ogni esecuzione la porta cambiava (se non specificata direttamente dall'utente).

**Comment by moty66** [comment]
faccio un commit tra poco, giusto per darvi idea di come la penso

**Comment by drego85** [comment]
Grazie ;) io don dovuto uscire di fretta! A dopo...
