### ISSUE TITLE
Output in json, txt and xml format - was Validation in UI

### ISSUE THREAD

**Issue by moty66** [drego85/DDoS-PHP-Script#18]
Do we really need the validation in ui.html https://github.com/drego85/DDoS-PHP-Script/blob/master/ui.html#L45

**Comment by TheZ3ro** [comment]
Serve?
Alla fine pensavo, tutti i controlli stanno nel PHP, non c'è bisogno di controllare molto.

Più che altro sarebbe bello che il PHP potesse ritornare un oggetto JSON con delle API Rest :D

**Comment by moty66** [comment]
perche no :+1:

**Comment by TheZ3ro** [comment]
Cosi la UI gestisce meglio le chiamate Ajax, aggiungiamo alla To-Do?

**Comment by moty66** [comment]
direi di si

**Comment by moty66** [comment]
possiamo fare cosi

in POST 
<pre>{
host: 'host',
port: 'port_number',
.. ecc ecc
}</pre>

la risposta
<pre>{
status: 'error|success'
message: 'error_message|success_message'
results: {host:'',port:''.. ecc ecc}
}</pre>

non dovrebbe essere complicato fare il tutto

**Comment by TheZ3ro** [comment]
Si, direi che ci può stare

**Comment by moty66** [comment]
I am working on it!

**Comment by moty66** [comment]
Potete fare il checkout della mia repos? ho fatto un sacco di modifiche, ma ancora non ho finito

**Comment by drego85** [comment]
:D ho creato un mostro, avevo detto che i LOG non era una priorità! Grazie

Il 11/08/15 15:48, Motaz Abuthiab ha scritto:

**Comment by moty66** [comment]
Ho fatto un po di test, mi sembra che funziona tutto alla perfezione

**Comment by drego85** [comment]
Confermo, anche per me tutto OK! L'ho provato prima ;)
