### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Rhozlid** [drego85/DDoS-PHP-Script#23]
hello, when i try to start the script, i get this error:

syntax error, unexpected T_FUNCTION in /home/...../public_html/..../ddos.php on line 518

**Comment by moty66** [comment]
Which version of php do you use?

**Comment by Rhozlid** [comment]
PHP Version 5.2.17

**Comment by moty66** [comment]
<pre>
array_walk_recursive($this->output, function($value, $key)use($xml){
	$xml->addChild($key, $value);
});
</pre>

You have to update your php to 5.4 to use this script, takea look here for more information about the callback and callable types http://php.net/manual/en/language.types.callable.php

**Comment by Rhozlid** [comment]
thank you so much for the reply
