### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by moffa13** [drego85/DDoS-PHP-Script#24]
Hi, maybe you can add a bandwidth limit

**Comment by moty66** [comment]
I am not sure that fwrite can handle this. I really have no idea how to do it in php.

Do you have any suggestion? feel free to make a pull request ;)

**Comment by SANGED** [comment]
I found an amazing AntiDDOS system that handle any DDOS attack system i know, in PHP! @moty66 ! 
Check it out: https://github.com/Sanix-Darker/AntiDDOS-system
