### ISSUE TITLE
About UPD Ports

### ISSUE THREAD

**Issue by diego3** [drego85/DDoS-PHP-Script#25]
Hi,

I just give a try and i noticed that it open a lot of upd "connections" with a lot of random ports, but in my pc (using windows) the firewall blocked all of them(ports), then while the attack was going on i tried to access my local web site and i wasn't be able to notice any changes! It is my local web site supposed to be down while attacking ? I mean that the attack doesn't worked to me and i dont know why exactly!

To the attack be executed successfully the ports accessed during the attack need be passed through the firewall? Or not neccessary?

I am noob in this subject and please forgive my poor english haha :)

**Comment by Benwebdev** [comment]
Yes this will flood your Localhost if you point it at it. Don't mess with scripts like this. 

Thanks 
Ben.

**Comment by moty66** [comment]
@diego3 Yes, you need to disable the firewall on your PC to enable the UDP flood, and this script suppose to block your local network if you try to make lot of requests with large packets.

**Comment by diego3** [comment]
@moty66  Thanks, that's the point!
