### ISSUE TITLE
Password.

### ISSUE THREAD

**Issue by richardjohnson23** [drego85/DDoS-PHP-Script#35]
When i'm trying to type the password(default: apple as backend.php says) in webpage console it's showing me the backend.php script without launching the attack. The webserver is Ubuntu 16.04.05 LTS and i'm using Google Chrome. Version of PHP installed in the webserver: PHP 7.0.30-0ubuntu0.16.04.1 (cli) on apache2.

**Comment by drego85** [comment]
Fixed.
